server:
  port: ${PORT:8080}
api:
  base-path: "/api/v1"
spring:
  application:
    name: thoughty-users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/thoughty}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  issuer: https://domain.com
  audience: https://domain.com
  signing:
    privateKey: "-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDP3Fc10WGWg9NF
69dwU31/mVU5mud58L7lc4Fn8OjqYHzgZX5SZKGTuFtAMhzHcvP5rgqIGvW5nv+x
Q2Zeym7vGpUjpV2Jr+RB4sAAkuMs2j2wx4LerevGuf9Cf4dsI+4szI86USLM0lBM
AxhpmQ6YWP8Pr6eoNyKBVO0yKDM9gR26613AiB0qtzG2ukS+wzXonXMFEd0fO0eV
FdQPgmnuQVBE+0oXeIhA6L0VLOm9MlA20aVlrrz96np0UQkRlLb5H0rwX5YDYhGC
Ql8tCtKRza7QCduWXpPsQgUkVQQz4SLJLbn920UhL642VY/t7/BofLS0lNvhb7Hs
5XkY8ujHAgMBAAECggEACcDoG5pF8MnMxj9+fF8syLge31GrXrzk6EOeCIzmnz1L
mz1PEgg9QLgGqCG49YtiVrlLoIznwHG0UgugKDei3TC5lGD0MsnkA4Pjj6pxRr3a
AhmuGdmFZDTUGZzTc51Cq0gmc39O7teA5xH6HPJj/0SJXS/YU9Em8Fg5u1VW6GkO
XHtJIhle3XJVHhMrbcPrrALbFP4PovgJ8D3zBOCVgkKmHJD2SXpW/PuPhw+ZLt9m
JESKMOnMeFVl5qyOeFi94ELzNuj1XXfC2VSXqXoPzk/fTqEFMyq4y4zLrj0JsI27
KYrnZWV3LPuPTN7lq7+NXjYUAdE3cGI4NqH6dc1p0QKBgQD1psQupAirG9axw0ZV
t+cITLcAikWUn4xo/D8qDyB0v6SxuOEu0FsZXVO2CBWMhczGO4qokB/wm8CNxzuY
GKZKdgmUFV0yWH8Owu2wWcorj9gyZgDNVDdXwDQ3HcxQ4XaAdJvpUFWd1X4xTvtI
xJv8dfu83IjVNTvl53nImmrxuQKBgQDYngT0qxfj9o/aKj3pToY4/dr18nA3W1mf
wokfLhlouNVTPOttT/90G01RypOTGiNZFEJVezMhj5Sw7V35PFVvqBj3rcYbBeRT
VyTfYS6oLdHCR9calOzA1Zhq/zaZH8ux4kIPsqOtGqV8df38r460p1w4UBQPpBmz
U/FUHAPufwKBgQDOfUUxc3853efFe0D3MuQITPwTfydn/Al6AndR8m801BcrsR3Q
TSIWmyWPwRHkEmCETW6LrMK8bSAZzVxhyG6X7sq0aJTzigIbtW05LPDNV1fDXYzV
DDKNF6qMngauAieraNnZ8EZXqystZZfCnkoEmGRoZ/S5S8sywTXUk0DMOQKBgBi9
a3l6NP9PQLy9CFcmJcRKkgB3EQPxhfnuIPUTsck5GvwnwAe7FETxfVIzHcm2OYVK
AA19Rai2mlfetFXr4yIeg8N98FtTv/EYydhNZCPHH+bdh568lZGsk3zc6yJv9Da7
zam3UGRL38yoOTrr3hOZ7blsw+3JYzoNA0oE7RoHAoGACgNBqq9AlK2T1/LQfuI8
bzoZUiS8HVml1Jqr8vnYeGnUqezo66+tgWO55UWlmCmJNa7N/tyPbbAYrm7cO5s4
y6GvDdoEGMKc2UxJc4VkY4VL2wGz8UjeHxOq9rLDopy114LCXtHC+n5voEe4BWWi
lFG1Z9RwADohKPJIBR2x2/Q=
-----END PRIVATE KEY-----"
    publicKey: "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz9xXNdFhloPTRevXcFN9
f5lVOZrnefC+5XOBZ/Do6mB84GV+UmShk7hbQDIcx3Lz+a4KiBr1uZ7/sUNmXspu
7xqVI6Vdia/kQeLAAJLjLNo9sMeC3q3rxrn/Qn+HbCPuLMyPOlEizNJQTAMYaZkO
mFj/D6+nqDcigVTtMigzPYEduutdwIgdKrcxtrpEvsM16J1zBRHdHztHlRXUD4Jp
7kFQRPtKF3iIQOi9FSzpvTJQNtGlZa68/ep6dFEJEZS2+R9K8F+WA2IRgkJfLQrS
kc2u0Anbll6T7EIFJFUEM+EiyS25/dtFIS+uNlWP7e/waHy0tJTb4W+x7OV5GPLo
xwIDAQAB
-----END PUBLIC KEY-----"
