server:
  port: ${PORT:8080}

api:
  base-path: "/api/v1"

spring:
  application:
    name: thoughty-users
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/thoughty}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000     # default 30_000
      validation-timeout: 1000      # default 5000
      max-lifetime: 60000           # default 30min
      keepalive-time: 30000
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:secret}
      timeout: 5000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
  lifecycle:
    timeout-per-shutdown-phase: 5s
  docker:
    compose:
      enabled: false

logging:
  level:
    org.testcontainers: DEBUG

# Just for local development
token:
  issuer: https://domain.com
  audience: https://domain.com
  signing:
    privateKey: "-----BEGIN PRIVATE KEY-----
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***=
-----END PRIVATE KEY-----"
    publicKey: "-----BEGIN PUBLIC KEY-----
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
-----END PUBLIC KEY-----"
